### ISSUE TITLE
Compill

### ISSUE THREAD

**Issue by chris1111** [SunnyKi/bareBoot#2]
Please put the Infos how to compiling this Bootloader
more people will use it if they know how to compile it in OS X environment
Thanks

**Comment by SunnyKi** [comment]
**Just create workspace dir for the project:**
mkdir ~/Workspace; cd ~/Workspace

**Grab necessary sources:**
git clone https://github.com/SunnyKi/bareBoot.git bareBoot 
svn co https://svn.code.sf.net/p/edk2/code/trunk edk2

**Make necessary toolchain:**
cd edk2; make -C BaseTools/Source/C; cd ..
wget https://www.dropbox.com/s/zddw0krebnei6gn/stuff.zip; unzip stuff.zip && rm stuff.zip
./build_gcc6.sh && rm ./build_gcc6.sh; ./buildnasm.sh && rm ./buildnasm.sh
cp -v ./Conf/* ./edk2/Conf/ && rm -rf ./Conf

**And now we ready make bareBoot (cbuild.sh have some options, details inside it)...**
cd bareBoot
./cbuild.sh 
result in ~/Workspace/Build
**... or release**
./release.sh
result in ~/Workspace/bb_${VERSION}.zip

**~/Workspace/bb directory contains instructions, bootsectors, EFI dir sample etc**
